### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by gyje** [Lyttoni/segspider#1]
1. 请问A段扫描大概多久？
2. 为什么有两个py文件，能更新一下READMD吗?
谢谢!

**Comment by Lyttoni** [comment]
吃惊，竟然有人关注了我的工具。
不太建议扫描A段，因为真的太庞大了，光是全部加载到队列，都能把好几G的内存吃满。
今晚已经更新README了，感谢关注。新增了对文件中的IP进行扫描。
